# Generated by Django 4.0.5 on 2022-06-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('national', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('barnch', models.CharField(max_length=50)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.courses')),
            ],
        ),
    ]
