# Generated by Django 4.0.5 on 2022-06-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='courses',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trainee.courses'),
        ),
    ]
